### BASE ###
/:
  controller: Base
  action: Default

/tableau-de-bord:
  controller: Base
  action: dashboard

### SECURITY ###
/resgister:
  controller: Security
  action: register
/s-inscrire:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/se-connecter:
  controller: Security
  action: login


/logout:
  controller: Security
  action: logout


/liste-des-utilisateurs:
  controller: Security
  action: listofusers

### POST ###

/add-post:
  controller: Post
  action: postajoute

/liste-post:
  controller: Post
  action: default

/post-delete:
  controller: Post
  action: postdelete

/edit-post:
  controller: Post
  action: postedit
/post:
  controller: Post
  action: post