############
### BASE ###
############

/:
  controller: Base
  action: Default

/admin/tableau-de-bord:
  controller: Base
  action: dashboard

################
### SECURITY ###
################

/resgister:
  controller: Security
  action: register
/s-inscrire:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/se-connecter:
  controller: Security
  action: login


/logout:
  controller: Security
  action: logout

/recuperationmdp:
  controller: Security
  action: recuperationmdp

/liste-des-utilisateurs:
  controller: Security
  action: listofusers

############ 
### POST ###
############

/admin/add-post:
  controller: Post
  action: postajoute

/admin/liste-post:
  controller: Post
  action: default

/admin/delete-post:
  controller: Post
  action: postdelete

/admin/edit-post:
  controller: Post
  action: postedit
/post:
  controller: Post
  action: post
/admin/edit-cat-post:
  controller: Post
  action: UpdatePostCat
/single-post:
  controller: Post
  action: public_single_post
  

###################
### COMMENTAIRE ###
###################

/add-commentaire:
  controller: Commentaire
  action: commentaireajoute
/admin/liste-commentaire:
  controller: Commentaire
  action: default 
/admin/delete-commentaire:
  controller: Commentaire
  action: commentairedelete
/admin/commentaire:
  controller: Commentaire
  action: commentaire

####################
### Utilisateurs ###
####################

/admin/users/liste-utilisateurs:
  controller: User
  action: default

/admin/users/edit:
  controller: User
  action: useredit

/admin/users/delete:
  controller: User
  action: userdelete

/admin/users/liste-utilisateurs-deleted:
  controller: User
  action: corbeille

/admin/users/delete-def:
  controller: User
  action: userdelete_definitely

/admin/users/restaurer:
  controller: User
  action: userrestaurer
/admin/user:
  controller: User
  action: User


/admin/valider-user:
  controller: User
  action: valideruser

###############
###installer###
###############

/installer:
  controller: Installer
  action: initialisation
/make-install:
  controller: Installer
  action: makeInstall


###############
#####Pages#####
###############

/admin/liste-Pages:
  controller: Page
  action: default

/admin/add-page:
  controller: Page
  action: addpage

/admin/add-page-send:
  controller: Page
  action: create

/admin/page-delete:
  controller: Page
  action: delete

/admin/page-edit:
  controller: Page
  action: editpage

/admin/edit-page-send:
  controller : Page
  action: editer

###############
###Catégorie###
###############

/admin/liste-categorie:
  controller: Categorie
  action: default

/admin/add-categorie:
  controller: Categorie
  action: add

/admin/cat-delete:
  controller: Categorie
  action: delete

###############
#####Menu######
###############

/admin/menu:
  controller: Menu
  action: default

/admin/menu/add:
  controller: Menu
  action: add

/admin/menu/remove:
  controller: Menu
  action: remove

  /admin/menu/is_accueil:
    controller: Menu
    action: addaccueil